name: Building and deployment app
on:
#   branch_protection_rule:
#     types: [created, edited]
  push:
    branches: [ dev ]
  pull_request:
    types:
      - closed
    branches: [ dev ]
env: 
  FRONT_CONTAINER: lysetskyiv/officespace-user:latest
  ADMIN_CONTAINER: lysetskyiv/officespace-admin:latest 
  BACK_CONTAINER: lysetskyiv/officespace-backend:latest

jobs:
  run_app:
    if: ${{ github.event.pull_request.merged }}
    runs-on: ubuntu-latest
    steps:
      - name: install zip
        run: sudo apt install -y zip

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: create .env for frontend_user
        run: echo ${{ secrets.ENV_FRONT_USER }} >> packages/frontend_user/.env

      - name: create .env for backend
        run: echo ${{ secrets.ENV_BACK }} >> packages/backend/.env

      - name: yarn install 
        run: yarn install

      - name: lint files 
        run: yarn lint

      - name: Build and push frontend
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ env.FRONT_CONTAINER }}

      - name: Build and push backend
        uses: docker/build-push-action@v3
        with:
          context: "./packages/backend/"
          push: true
          tags: ${{ env.BACK_CONTAINER }}

      - name: Build and push admin
        uses: docker/build-push-action@v3
        with:
          context: "./packages/backend/"
          push: true
          tags: ${{ env.ADMIN_CONTAINER }}
      

      - id: ssh_cleanup
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: Cleanup server  
        continue-on-error: true
        run: ssh ${{ steps.ssh_cleanup.outputs.SERVER }}  "docker rmi $(docker images -a -q) || true; docker stop $(docker ps -a -q) || true; docker rm $(docker ps -a -q) || true; docker rmi $(docker images -a -q) || true" 
        
       

      - id: ssh_pull
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: pull containers  
        continue-on-error: true
        run: ssh ${{ steps.ssh_pull.outputs.SERVER }}  "docker pull $FRONT_CONTAINER; docker pull $ADMIN_CONTAINER; docker pull $BACK_CONTAINER" 
      
      
      - id: ssh_run
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh_run.outputs.SERVER }}  "docker run -d -p 81:80 $FRONT_CONTAINER; docker run -d -p 4000:4000 $BACK_CONTAINER; docker run -d -p 82:80 $ADMIN_CONTAINER;"

      - id: ssh_restart_nginx
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh_restart_nginx.outputs.SERVER }}  "sudo service nginx restart"  