name: Building and deployment app
on:
#   branch_protection_rule:
#     types: [created, edited]
  push:
    branches: [ WBS-8 ]
  pull_request:
    branches: [ WBS-8 ]

jobs:
  run_app:
    runs-on: ubuntu-latest
    steps:
      - name: install zip
        run: sudo apt install -y zip

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache modules
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 18

      # - name: Build frontend_admin 
      #   run: cd packages/frontend_admin && yarn && CI=false && yarn build

      # - name: Build frontend_user 
      #   run: cd packages/frontend_user && yarn && CI=false && yarn build
      
      - id: ssh_mkdir
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - run:  ssh ${{ steps.ssh_mkdir.outputs.SERVER }} "cd /home/ubuntu; rm -rf frontend_user frontend_admin; mkdir frontend_user frontend_admin; chmod 777 frontend_admin/ frontend_user/"

      - name: ssh_copy
        run: | 
          scp ${{ secrets.SSH_KEY }} packages/frontend_user/build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/frontend_user
          scp ${{ secrets.SSH_KEY }} packages/frontend_admin/build/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/ubuntu/frontend_admin


      - id: ssh_move
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh_move.outputs.SERVER }} "sudo cp -r /frontend_admin/build /var/www/html/admin/build; sudo cp -r /frontend_user/build /var/www/html/user/build; rm -rf frontend_user frontend_admin"

      - id: ssh_run
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh_run.outputs.SERVER }}  "rm -rf officespace-booking; pm2 delete 0; git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY; cd officespace-booking; git checkout WBS-8; git pull; cd scripts; . build.sh" 