name: Instance Rebooting
on:
#   branch_protection_rule:
#     types: [created, edited]
  push:
    branches: [ WBS-8 ]
  pull_request:
    branches: [ WBS-8 ]
jobs:
  login_reboot:
    runs-on: ubuntu-latest
    steps:
      # - run: sudo apt install -y zip
      # - uses: actions/checkout@v3
      #   with:
      #     fetch-depth: 0
      - id: ssh
        uses: invi5H/ssh-action@v1
        with:
              SSH_HOST: ${{ secrets.SSH_HOST }}
              SSH_PORT: ${{ secrets.SSH_PORT }}
              SSH_USER: ${{ secrets.SSH_USER }}
              SSH_KEY: ${{ secrets.SSH_KEY }}
      - run: ssh ${{ steps.ssh.outputs.SERVER }}  "rm -rf officespace-booking; pm2 delete 0; git clone ${{ secrets.GIT_REPO }}; cd officespace-booking; git checkout WBS-8; git pull; cd scripts; . build.sh"