name: Linting app
on:
#   branch_protection_rule:
#     types: [created, edited]
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: install zip
        run: sudo apt install -y zip

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: create .env for frontend_user
        run: echo ${{ secrets.ENV_FRONT_USER }} >> packages/frontend_user/.env

      - name: create .env for backend
        run: echo ${{ secrets.ENV_BACK }} >> packages/backend/.env

      - name: yarn install 
        run: yarn install


      - name: lint files 
        run: yarn lint

      